channels:
- conda-forge
dependencies:
- python=3.10.18
- pip<=25.2
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.2.6
  - pandas==2.3.2
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
